# 02807 - Week 2 Exercises


## Learning objectives:

* Run Python code in Colab or Jupyter notebooks
* Get hands-on experience storing, manipulating and extracting data efficiently with NumPy.
* Perform optimised computations on arrays using NumPy’s vectorised functions. 
* Compare the performance of simple non-vectorised operations to vectorised one. 


## Readings:

### **Numpy**:

Main reading:

* [Chapter 2: Introduction to Numpy](https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html). Python Data Science Handbook.

Supplementary readings:

* [A Visual Intro to NumPy and Data Representation](https://jalammar.github.io/visual-numpy/)
* [Guide to NumPy resources: beginner, intermediate and advanced](https://e2eml.school/numpy_resources.html)



## Exercise 1: importing NumPy

### **1. Import numpy as np and print the version number**


In [25]:
print("Solution")
import numpy as np

Solution


## Exercise 2: creating arrays

### a. Create a 1D array of numbers from 0 to 9

Desired output: 
```
Solution
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [1]:
print("Solution")
arr = [i for i in range(10)]
arr

Solution


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

### b. Create a 3×3 Boolean array of all `True`’s

Desired output: 

```
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])
```

In [22]:
print("Solution")
# [expression for item in iterable if condition == True]
arr1 = [[True for i in range(3)] for i in range(3)]
arr1

Solution


[[True, True, True], [True, True, True], [True, True, True]]

### c. Create a 5 x 3 x 4 array randomly filled with integers between 0 and 4, inclusive:

hint: ``np.random.randint``

Example of desired output:

```
array([[[3, 4, 0, 4],
        [2, 3, 4, 4],
        [0, 2, 4, 2]],

       [[2, 1, 3, 0],
        [4, 3, 2, 2],
        [2, 1, 2, 4]],

       [[3, 1, 1, 1],
        [4, 4, 0, 1],
        [0, 2, 3, 0]],

       [[3, 0, 3, 3],
        [4, 0, 3, 3],
        [3, 3, 0, 1]],

       [[3, 2, 2, 2],
        [0, 1, 1, 4],
        [4, 2, 1, 0]]])

```

In [27]:
print("Solution")
[[[np.random.randint(5) for i in range(4)] for j in range(3)] for k in range(5)]

Solution


[[[4, 3, 3, 3], [4, 1, 4, 4], [2, 3, 3, 2]],
 [[2, 2, 3, 2], [0, 2, 4, 4], [1, 3, 0, 2]],
 [[2, 4, 0, 1], [4, 0, 1, 0], [2, 3, 0, 3]],
 [[3, 3, 3, 1], [4, 4, 4, 1], [3, 0, 1, 3]],
 [[4, 2, 3, 0], [2, 1, 1, 0], [2, 3, 1, 4]]]

## Exercise 3: universal functions and vectorisation (part 1). Faster dot product.

The dot product is an algebraic operation which takes two equal-sized vectors and returns a single scalar. For two vectors $\mathbf{x}$ and $\mathbf{y}$, their dot product is defined as:

$$\mathbf{x} \cdot \mathbf{y} = \sum_{i=1}^{n}x_iy_i = x_1y_1 + x_2y_2 + … + x_ny_n$$

Let's consider the following vectors.

In [15]:
X = np.random.rand(100000)
Y = np.random.rand(100000)

In Python, one way to calulate the dot product is to iterate over the number of elements in the vectors, multiplying their $i$-th elements, and accumulating the result:

In [16]:
def dot_slow_1(x,y):
    """"Dot product by looping over elements and multiplying them"""
    s = 0 
    for i in range(x.size):
        s += x[i] * y[i]
    return s

A more succinct and pythonic way to do this would be to use list comprehension:

In [17]:
def dot_slow_2(x, y):
    """Dot product as sum of list comprehension doing element-wise multiplication"""
    return sum(x_i * y_i for x_i, y_i in zip(x, y))

Let's look at the performance we get computing dot products in this way.

In [18]:
print("Time and memory use of dot_slow_1:")
%timeit dot_slow_1(X, Y)

print("Time and memory use of dot_slow_2:")
%timeit dot_slow_2(X, Y)

Time and memory use of dot_slow_1:
22.3 ms ± 615 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
Time and memory use of dot_slow_2:
16.5 ms ± 341 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### Use NumPy's vectorised operations to define a function that computes the dot product.

In [19]:
def my_dot(x, y):
  # your solution goes here
  raise NotImplementedError

Use `%timeit` to check the performance of your function. How much faster did we get with vectorisation? If you did things right, your solution should run in *µs*, running around 1000x faster per loop than the non-vectorised `dot_slow` functions.

In [20]:
print("Time and memory use of my_dot:")
%timeit my_dot(X, Y)

Time and memory use of my_dot:


NotImplementedError: 

## Exercise 4: universal functions and vectorisation (part 2). Buying low, selling high.

Let's look at a more interesting problem. Here's a classic technical interview problem:

> Given a stock’s price history as a sequence, and assuming that you are only allowed to make one purchase and one sale, what is the maximum profit that can be obtained? For example, given prices = (20, 18, 14, 17, 20, 21, 15), the max profit would be 7, from buying at 14 and selling at 21.



The straighforward solution, with $O(n^2)$ [time complexity](https://www.hackerearth.com/practice/basic-programming/complexity-analysis/time-and-space-complexity/tutorial/), consists of taking every combination of two consecutive prices and determining the maximum difference.

However, there's also an $O(n)$ solution that consists of iterating through the sequence just once and finding the difference between each price and a running minimum. Here's an non-vectorised implementation:


In [ ]:
def profit(prices):
    max_price = 0
    min_price = prices[0]
    for price in prices[1:]:
        min_price = min(min_price, price)
        max_price = max(price - min_price, max_price)
    return max_price

prices = (20, 18, 14, 17, 20, 21, 15)
profit(prices)

Can this be done faster in NumPy? Certainly. But first, let’s create a more realistic example (using, of course, some trusty NumPy functions!):

In [ ]:
import numpy as np
# Set seed for randn below
np.random.seed(2)

# Create mostly NaN array with a few 'turning points' (local min/max).
prices = np.full(100, fill_value=np.nan)
prices[[0, 10, 50, 80, -1]] = [80., 30., 50., 70., 40.]

# Linearly interpolate the missing values and add some noise.
x = np.arange(len(prices))
is_valid = ~np.isnan(prices)
prices = np.interp(x=x, xp=x[is_valid], fp=prices[is_valid])
prices += np.random.randn(len(prices)) * 2

Let's look at the data with `matplotlib`. Don't worry if you don't get what goes on here. We'll learn how to use `matplotlib` for data visualisation in the coming weeks.

The idea is to buy low (green) and sell high (red):

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('classic')

# Warning! This isn't a fully correct solution, but it works for now.
# If the absolute min came after the absolute max, you'd have trouble.
mn = np.argmin(prices)
mx = mn + np.argmax(prices[mn:])
kwargs = {'markersize': 8, 'linestyle': ''}

fig, ax = plt.subplots()
ax.plot(prices)
ax.set_title('Price History')
ax.set_xlabel('Time')
ax.set_ylabel('Price')
ax.plot(mn, prices[mn], marker='o', color='g', **kwargs)
ax.plot(mx, prices[mx], marker='o', color='r', **kwargs)
plt.show()

What does a NumPy implementation look like? There is no `np.runmin()` that computes the running (or cumulative) minimum. However, NumPy’s universal functions (`ufunc`'s) all have an `accumulate()` method that does what its name implies:



In [ ]:
x = np.array([10,2,4,7,9,1,11,3])
runmin = np.minimum.accumulate
runmin(x)

Use `runmin` and other NumPy functions to define your own version of the `profit` function. Keeping the logic from the pure-Python example, you can find the difference between each price and a running minimum (element-wise), and then take the max of this sequence:

In [ ]:
def my_profit(prices):
     """Price minus cumulative minimum price, element-wise."""
     # your solution goes here
     raise NotImplementedError

Let's see the time performance of the original `profit` function on our dataset.

In [ ]:
print("The maximum profit is", profit(prices))
%timeit profit(prices)

How does `my_profit` compare? Your NumPy solution should do at least as well as the pure-Python solution over this small dataset (we're working with 100 data points). 

In [ ]:
print("The maximum profit is", my_profit(prices))
%timeit my_profit(prices)



Over a large dataset, you'll normally see significant performance differences. Our implementation of `my_profit` typically runs about 50x faster than `profit` over a random dataset with 1.000.000 datapoints. Do you get comparable results?

In [ ]:
rand_seq = np.random.randint(0, 100, size=1000000)
%timeit profit(rand_seq)
%timeit my_profit(rand_seq)

## Exercise 5: extracting information from arrays

Let's extract some potentially useful information from our `prices` dataset.


### a. Let's find all values in a given range. Extract all prices with values between 45 and 65 from the first 10 prices in `prices`.


In [ ]:
print("First 10 prices")
prices_small = prices[:10]
prices_small

In [ ]:
print("Solution")
# your solution goes here

### b. Let's say that you want to buy in the first time the price drops below 30. Let's find the first occurence of a value meeting a condition. 

Hint: use `np.argwhere`.

In [ ]:
# Solution
print("Solution")
# your solution goes here

### c. Let's get the *positions* and *values* of the top 5 prices overall. Use NumPy only to extract this information.

Hint: Use `np.argwhere` along with `np.percentile`, or sort and slice arrays

In [ ]:
# Solution
print("Positions of the top 5 prices")  
# your solution goes here
print("Values of the top 5 prices")
# your solution goes here

### d. Let's get some summary statistics. Print the mean, median and standard deviation of the list of prices.

The desired output is:

```
Mean, median and standard deviation: 50.770589574397285 50.45810666998631 12.125291517615116
```

In [ ]:
# Solution
# your solution goes here.

### e. Finally, let's find all the local maxima in the `prices` array. 

If you are up for the challenge, you can try to use NumPy functions only. Consider first how to achieve a boolean mask reflecting which `prices` are greater than the previous occurences. Then greater than the proceeding occurences. Using these two masks, it is possible to obtain the indices 

Otherwise, the package `scipy.signal` offers a nice function called `find_peaks`.

In [ ]:
# Solution
print("Local maxima")
# your solution goes here

Here are the maxima found with `scipy`.

In [ ]:
from scipy.signal import find_peaks

peaks, _ = find_peaks(prices, height=0)

If you store the local maxima in a variable called `peaks`, the following plot will mark them in green.

In [ ]:
kwargs = {'markersize': 8, 'linestyle': ''}

fig, ax = plt.subplots()
ax.plot(prices)
ax.set_title('Price History')
ax.set_xlabel('Time')
ax.set_ylabel('Price')
ax.plot(peaks, prices[peaks], marker='o', color='g', **kwargs)
plt.show()